[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Change this runner as required for your MCU.
runner = [
    "probe-rs",
    "run",
    "--chip",
    "STM32G431VBTx",
    "--speed",
    "5000",
    "--preverify",
    "--log-format",
    "{t} [{L}] {s}",
]


[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "4096"